### PR TITLE
require ActiveSupport module to provide String#remove

### LINKED ISSUE #421: `mrsk deploy` gives me ERROR (NoMethodError): undefined method `remove' for "Mrsk::Commands::Builder::Multiarch":String
% mrsk deploy      
```
Acquiring the deploy lock...
Log into image registry...
  INFO [91e5d11c] Running docker login -u [REDACTED] -p [REDACTED] as jason@localhost
  INFO [91e5d11c] Finished in 0.720 seconds with exit status 0 (successful).
  INFO [036062d9] Running docker login -u [REDACTED] -p [REDACTED] on 54.196.71.166
  INFO [036062d9] Finished in 0.154 seconds with exit status 0 (successful).
Build and push app image...
Releasing the deploy lock...
  Finished all in 1.4 seconds
  ERROR (NoMethodError): undefined method `remove' for "Mrsk::Commands::Builder::Multiarch":String

    target.class.to_s.remove("Mrsk::Commands::Builder::").underscore.inquiry
                     ^^^^^^^
```

**Rails 7.1.0.alpha**
**MRSK 0.15.1**

for reference, I am writing this (WIP) setup guide for MRSK on EC2
https://jasonfleetwoodboldt.com/courses/rails-7-crash-course/mrsk-on-amazon-ec2

### PR DESCRIPTION
**Pull request by fig**
`Mrsk::Commands::Builder#name` uses `String#remove` which is provided by the ActiveSupport module `active_support/core_ext/string/filters` but that module is not being required anywhere in the code base.

For some reason, the tests pass without this fix. I can't figure out where the `active_support/core_ext/string/filters` module is being pulled into the test env.

fixes #421

### CODE REVIEW

**Comment by northeastprince** [comment]
@djmb could we get this merged? #421 is preventing deployments.

File: lib/mrsk/commands/builder.rb [hunk 1]
```diff
@@ -1,3 +1,5 @@
+require "active_support/core_ext/string/inquiry"
```
Comment (djmb) [inline lib/mrsk/commands/builder.rb:1]: This is already included in `lib/mrsk/configuration.rb`. Looks like we need to include `active_support/core_ext/string/filters` there as well now

**Comment by fig** [comment]
@northeastprince Rails edge will be Rails stable one day. We can't rely on dependencies brought in by other libraries.

**Comment by fig** [comment]
>  there are conflicts since the rename from MRSK to Kamal. Could you resolve those and I'll get this merged?

I _think_ the conflicts are resolved now :grey_question:
